window.APARTMENT_DATA_1BR = {
  "asOf": "2026-09-09",
  "listings": [
    {
      "id": "1br-back-nine",
      "name": "Back Nine Apartments \u2014 Unit 5",
      "complex": "Back Nine Apartments",
      "address": "2635 Prosch Ave W, Seattle, WA 98119",
      "lat": 47.6436,
      "lng": -122.3775,
      "region": "seattle",
      "cluster": "interbay",
      "corridor": "interbay-15th",
      "beds": 1,
      "baths": 1,
      "rentMin": 1565,
      "rentMax": 1565,
      "rangeNote": "592 sf; hardwood; quartz; heated bath floors; internet included (bring router)",
      "available": "now",
      "parking": "street parking (listing)",
      "parkingFee": 0,
      "ev": "unknown",
      "utils": "WSG via RUBS per occupant",
      "pets": "cats/small dogs \u226445 lbs; $50/mo; no deposit",
      "commuteA": "AM ~25\u201340 min over 520/I-5 to LWHS; 3pm ~20\u201335",
      "commuteB": "Excellent: west Queen Anne / Interbay near Expedia / D Line",
      "notes": "Sep 9 2026: NEW. Rentable Unit 5 $1,565 now. Boutique 8-unit; $0 Obligo deposit option. EV unknown \u2014 do not invent chargers.",
      "fit": "stretch",
      "url": "https://www.rentable.co/seattle-wa/2635-prosch-ave-w"
    },
    {
      "id": "1br-barrett",
      "name": "Barrett Apartments \u2014 Unit 206",
      "complex": "Barrett Apartments",
      "address": "2850 15th Ave W, Seattle, WA 98119",
      "lat": 47.646,
      "lng": -122.3762,
      "region": "seattle",
      "cluster": "interbay",
      "corridor": "interbay-15th",
      "beds": 1,
      "baths": 1,
      "rentMin": 1629,
      "rentMax": 1629,
      "rangeNote": "641 sf",
      "available": "now",
      "parking": "off-street / garage (confirm fee)",
      "parkingFee": null,
      "ev": "unknown",
      "utils": "confirm; water listed included on aggregator",
      "pets": "cats/dogs OK (listing)",
      "commuteA": "AM ~25\u201340 min over 520/I-5 to LWHS; 3pm ~20\u201335",
      "commuteB": "Excellent: Interbay / 15th Ave W near Expedia / D Line",
      "notes": "Sep 8 2026: NEW. Rentable Unit 206 $1,629 now. Stretch/budget for B. Same building has renovated 2BRs from $2,195 on 2BR board. EV unknown. Sep 9 recheck: still live at prior rent on Rentable.",
      "fit": "stretch",
      "url": "https://www.rentable.co/seattle-wa/2850-15th-ave"
    },
    {
      "id": "1br-dor-rik",
      "name": "Dor-rik \u2014 Unit 307",
      "complex": "Dor-rik",
      "address": "2655 14th Ave W, Seattle, WA 98119",
      "lat": 47.6438,
      "lng": -122.375,
      "region": "seattle",
      "cluster": "interbay",
      "corridor": "interbay-15th",
      "beds": 1,
      "baths": 1,
      "rentMin": 1495,
      "rentMax": 1495,
      "rangeNote": "750 sf; updated finishes",
      "available": "now",
      "parking": "+$20/mo when available (listing)",
      "parkingFee": 20,
      "ev": "unknown",
      "utils": "WSG ~$50/person/mo; electric separate; coin laundry",
      "pets": "case-by-case under 35 lb; deposit/rent (listing)",
      "commuteA": "AM ~25\u201340 min over 520/I-5 to LWHS; 3pm ~20\u201335",
      "commuteB": "Excellent: Queen Anne west slope / Interbay near Expedia",
      "notes": "Sep 8 2026: NEW. Rentable Unit 307 $1,495 now (updated today). Strong budget 1BR for B. EV unknown \u2014 do not invent chargers. Sep 9 recheck: still live at prior rent on Rentable.",
      "fit": "budget",
      "url": "https://www.rentable.co/seattle-wa/2655-14th-ave-w"
    },
    {
      "id": "1br-skyline-units",
      "name": "Skyline Units \u2014 Unit 2",
      "complex": "Skyline Units",
      "address": "2821 14th Ave W, Seattle, WA 98119",
      "lat": 47.6455,
      "lng": -122.375,
      "region": "seattle",
      "cluster": "interbay",
      "corridor": "interbay-15th",
      "beds": 1,
      "baths": 1,
      "rentMin": 1450,
      "rentMax": 1450,
      "rangeNote": "628 sf; $300 moving incentive mentioned on listing",
      "available": "now",
      "parking": "dedicated space +$50/mo (listing)",
      "parkingFee": 50,
      "ev": "unknown",
      "utils": "WSG flat ~$100/mo; electric separate",
      "pets": "1 dog under 45 lb / 1 cat (listing)",
      "commuteA": "AM ~25\u201340 min over 520/I-5 to LWHS; 3pm ~20\u201335",
      "commuteB": "Excellent: Interbay / Queen Anne west slope near Expedia / D Line",
      "notes": "Sep 8 2026: NEW. Rentable Unit 2 $1,450 now (updated today). North Pacific Properties. Strong budget 1BR for B. EV unknown \u2014 do not invent chargers. Sep 9 recheck: still live at prior rent on Rentable.",
      "fit": "budget",
      "url": "https://www.rentable.co/seattle-wa/2821-14th-ave-w"
    },
    {
      "id": "1br-124th-a3",
      "name": "14321 124th Ave NE #A3",
      "complex": "124th Ave NE",
      "address": "14321 124th Ave NE #A3, Kirkland, WA 98034",
      "lat": 47.7304,
      "lng": -122.1765,
      "region": "eastside",
      "cluster": "totem-lake",
      "corridor": null,
      "beds": 1,
      "baths": 1,
      "rentMin": 1750,
      "rentMax": 1750,
      "rangeNote": "W/S/G in rent",
      "available": "now",
      "parking": "dedicated covered + guest",
      "parkingFee": 0,
      "ev": "no",
      "utils": "W/S/G included; electric PSE",
      "pets": "unknown",
      "commuteA": "AM ~12\u201318 min via 405/132nd",
      "commuteB": "~70\u201390 min bus/405 \u2192 Seattle \u2192 D Line",
      "notes": "Kingsgate/Totem Lake condo. Strong for A.",
      "fit": "stretch",
      "url": "https://www.apartments.com/14321-124th-ave-ne-kirkland-wa-unit-a3/djp1fyk/"
    },
    {
      "id": "1br-evergreen-127",
      "name": "Evergreen Hill condo",
      "complex": "Evergreen Hill",
      "address": "14517 127th Ln NE, Kirkland, WA 98034",
      "lat": 47.7337,
      "lng": -122.1702,
      "region": "eastside",
      "cluster": "kingsgate",
      "corridor": null,
      "beds": 1,
      "baths": 1,
      "rentMin": 1750,
      "rentMax": 1750,
      "rangeNote": "Top floor; wood-burning fireplace",
      "available": "now",
      "parking": "uncovered assigned #4",
      "parkingFee": 0,
      "ev": "no",
      "utils": "water/sewer/trash included; electric",
      "pets": "unknown",
      "commuteA": "AM ~12\u201320 min",
      "commuteB": "~70\u201390 min same Eastside\u2192Seattle\u2192D pattern",
      "notes": "Kingsgate. EV no.",
      "fit": "stretch",
      "url": "https://www.apartmentlist.com/wa/kirkland/clean-top-floor-1br-1ba-condo-with-wood-burning-fireplace"
    },
    {
      "id": "1br-houghton-520",
      "name": "Houghton condo Unit 520",
      "complex": "Houghton",
      "address": "11012 NE 68th St, Kirkland, WA 98033",
      "lat": 47.6679,
      "lng": -122.1927,
      "region": "eastside",
      "cluster": "houghton",
      "corridor": null,
      "beds": 1,
      "baths": 1,
      "rentMin": 1795,
      "rentMax": 1795,
      "rangeNote": "W/S/G + internet/cable listed included",
      "available": "likely gone \u2014 confirm with PM",
      "parking": "1 space + storage locker",
      "parkingFee": 0,
      "ev": "no",
      "utils": "W/S/G + internet/cable incl per listing",
      "pets": "unknown",
      "commuteA": "~8\u201312 min \u2014 best A drive on the 1BR list",
      "commuteB": "~65\u201385 min 405/520 \u2192 Seattle \u2192 D",
      "notes": "Sep 5 2026: Sep 4 check treated as gone; Rent.com still mirrors $1,795 but no clear live availability \u2014 treat as stale until MacPherson confirms.",
      "fit": "gone",
      "url": "https://www.apartmentfinder.com/Washington/Kirkland-Apartments/1-Bed-1-Bath-Houghton-Condo-In-Kirkland-1795-Month-Apartments-nd3mbgm"
    },
    {
      "id": "1br-northpointe",
      "name": "Northpointe Highlands",
      "complex": "Northpointe Highlands",
      "address": "17512 83rd Pl NE, Kenmore, WA 98028",
      "lat": 47.7544,
      "lng": -122.2287,
      "region": "eastside",
      "cluster": "kenmore-bothell",
      "corridor": null,
      "beds": 1,
      "baths": 1,
      "rentMin": 1720,
      "rentMax": 1745,
      "rangeNote": "C201/D204",
      "available": "~30 Sep 2026",
      "parking": "reserved included",
      "parkingFee": 0,
      "ev": "no",
      "utils": "utilities extra",
      "pets": "unknown",
      "commuteA": "AM ~18\u201328 min via Juanita/405",
      "commuteB": "~60\u201380 min ST/KCM \u2192 Seattle or Link",
      "notes": "Kenmore. Oct-ish availability.",
      "fit": "stretch",
      "url": "https://northwest.appfolio.com/listings/detail/788a2bdb-36eb-4a4a-a906-f8c45a239d20"
    },
    {
      "id": "1br-polaris-eastgate",
      "name": "Polaris at Eastgate 1BR",
      "complex": "Polaris at Eastgate",
      "address": "13300 SE Eastgate Way, Bellevue, WA 98005",
      "lat": 47.5807,
      "lng": -122.1645,
      "region": "eastside",
      "cluster": "eastgate",
      "corridor": "i90",
      "beds": 1,
      "baths": 1,
      "rentMin": 1630,
      "rentMax": 1768,
      "rangeNote": "LIHTC / income-restricted",
      "available": "recently listed",
      "parking": "free surface; garage $150 long wait",
      "parkingFee": 0,
      "ev": "listing",
      "utils": "income-restricted; W/S/G often paid",
      "pets": "unknown",
      "commuteA": "AM ~25\u201335 min via 405",
      "commuteB": "Strong: Eastgate P&R / South Bellevue 2 Line \u2192 D. ~50\u201370 min",
      "notes": "Only if they qualify. Confirm EV claim in writing.",
      "fit": "budget",
      "url": "https://www.liveatpolarisateastgate.com/"
    },
    {
      "id": "1br-zinnia",
      "name": "Zinnia 1BR",
      "complex": "Zinnia",
      "address": "2318 N 147th St, Shoreline, WA 98133",
      "lat": 47.7362,
      "lng": -122.3307,
      "region": "seattle",
      "cluster": "shoreline",
      "corridor": "link-north",
      "beds": 1,
      "baths": 1,
      "rentMin": 1498,
      "rentMax": 1600,
      "rangeNote": "~515 sf; MFTE ~$1600; market higher",
      "available": "listed",
      "parking": "gated multi-level garage",
      "parkingFee": null,
      "ev": "yes",
      "utils": "typical RUBS / tenant electric",
      "pets": "unknown",
      "commuteA": "AM ~30\u201340 min via 522/405",
      "commuteB": "Shoreline South/148th 1 Line \u2192 Westlake \u2192 D. ~45\u201365 min",
      "notes": "Best dual compromise. Official EV charging. Small unit.",
      "fit": "budget",
      "url": "https://www.liveatzinnia.com/amenities"
    },
    {
      "id": "1br-brighton-north",
      "name": "Brighton North",
      "complex": "Brighton North",
      "address": "1549 NE 177th St, Shoreline, WA 98155",
      "lat": 47.7581,
      "lng": -122.3111,
      "region": "seattle",
      "cluster": "shoreline",
      "corridor": "link-north",
      "beds": 1,
      "baths": 1,
      "rentMin": 1495,
      "rentMax": 1595,
      "rangeNote": null,
      "available": "now (verify)",
      "parking": "parking garage",
      "parkingFee": null,
      "ev": "no",
      "utils": "ask RUBS",
      "pets": "unknown",
      "commuteA": "AM ~28\u201338 min",
      "commuteB": "Shoreline 175th / north Link \u2192 D. ~45\u201365 min",
      "notes": "North City. Strong Link-north split.",
      "fit": "budget",
      "url": "https://www.padmapper.com/buildings/p119557/brighton-north-apartments-at-1549-ne-177th-st-shoreline-wa-98155"
    },
    {
      "id": "1br-ballinger-404",
      "name": "Ballinger Apt Homes #404",
      "complex": "Ballinger",
      "address": "19921 19th Ave NE #404, Shoreline, WA 98155",
      "lat": 47.7736,
      "lng": -122.3105,
      "region": "seattle",
      "cluster": "shoreline",
      "corridor": "link-north",
      "beds": 1,
      "baths": 1,
      "rentMin": 1599,
      "rentMax": 1599,
      "rangeNote": "Sep free-rent promo listed",
      "available": "now",
      "parking": "reserved (ask)",
      "parkingFee": null,
      "ev": "no",
      "utils": "tenant utilities",
      "pets": "unknown",
      "commuteA": "AM ~30\u201340 min",
      "commuteB": "bus/Link north \u2192 D. ~50\u201370 min",
      "notes": "Ballinger. EV no.",
      "fit": "stretch",
      "url": "https://northwest.appfolio.com"
    },
    {
      "id": "1br-collins-junction",
      "name": "Collins Junction 1x1",
      "complex": "Collins Junction",
      "address": "4727 200th St SW, Lynnwood, WA 98036",
      "lat": 47.8175,
      "lng": -122.2972,
      "region": "seattle",
      "cluster": "lynnwood",
      "corridor": "link-north",
      "beds": 1,
      "baths": 1,
      "rentMin": 1577,
      "rentMax": 1811,
      "rangeNote": "3 left when checked",
      "available": "now",
      "parking": "assigned/surface lot",
      "parkingFee": null,
      "ev": "no",
      "utils": "ask",
      "pets": "unknown",
      "commuteA": "AM ~35\u201350 min via 405",
      "commuteB": "Lynnwood Link \u2192 1 Line \u2192 D. ~55\u201375 min",
      "notes": "Lynnwood. Stretch at the high end.",
      "fit": "stretch",
      "url": "https://collinsjunction.com/floorplans/1x1/"
    },
    {
      "id": "1br-twin-firs",
      "name": "Twin Firs",
      "complex": "Twin Firs",
      "address": "20220 60th Ave W, Lynnwood, WA 98036",
      "lat": 47.8155,
      "lng": -122.3142,
      "region": "seattle",
      "cluster": "lynnwood",
      "corridor": "link-north",
      "beds": 1,
      "baths": 1,
      "rentMin": 1575,
      "rentMax": 1575,
      "rangeNote": null,
      "available": "now",
      "parking": "off-street surface",
      "parkingFee": 0,
      "ev": "no",
      "utils": "RUBS",
      "pets": "unknown",
      "commuteA": "AM ~35\u201350 min",
      "commuteB": "near Link/Swift; 1 Line \u2192 D. ~55\u201375 min",
      "notes": "Lynnwood garden.",
      "fit": "stretch",
      "url": "https://www.rentalsource.com/details/20220-20230-60th-ave-w-lynnwood-wa-83963578/"
    },
    {
      "id": "1br-admiralty",
      "name": "Admiralty Way condo",
      "complex": "Admiralty",
      "address": "15101 Admiralty Way, Lynnwood, WA 98087",
      "lat": 47.86,
      "lng": -122.28,
      "region": "seattle",
      "cluster": "lynnwood",
      "corridor": "link-north",
      "beds": 1,
      "baths": 1,
      "rentMin": 1445,
      "rentMax": 1445,
      "rangeNote": "+$100 W/S flat",
      "available": "listed (verify freshness)",
      "parking": "1 off-street included",
      "parkingFee": 0,
      "ev": "no",
      "utils": "+$100 W/S; tenant power/garbage",
      "pets": "unknown",
      "commuteA": "AM ~40\u201355 min",
      "commuteB": "farther north of Lynnwood Link; bus to station \u2192 D. ~60\u201380 min",
      "notes": "Cheapest north condo. Confirm still live.",
      "fit": "budget",
      "url": "https://www.apartmentlist.com/wa/north-lynnwood/ideal-1-bed-1-bath-lynnwood-condo-with-w-d-in-unit"
    },
    {
      "id": "1br-67th-lynnwood",
      "name": "Quiet 8-unit 1BR",
      "complex": "67th Ave W",
      "address": "21011 67th Ave W, Lynnwood, WA 98036",
      "lat": 47.8084,
      "lng": -122.3232,
      "region": "seattle",
      "cluster": "lynnwood",
      "corridor": "link-north",
      "beds": 1,
      "baths": 1,
      "rentMin": 1350,
      "rentMax": 1350,
      "rangeNote": "small 8-unit building",
      "available": "now",
      "parking": "ask",
      "parkingFee": null,
      "ev": "no",
      "utils": "ask",
      "pets": "unknown",
      "commuteA": "AM ~35\u201350 min",
      "commuteB": "close to light rail & Swift \u2192 D. ~55\u201375 min",
      "notes": "Lowest asking 1BR in the set. Verify parking for EV.",
      "fit": "budget",
      "url": "https://rentberry.com"
    },
    {
      "id": "1br-contour",
      "name": "Contour Interbay (Summit 1x1)",
      "complex": "Contour",
      "address": "3036 16th Ave W, Seattle, WA 98119",
      "lat": 47.6475,
      "lng": -122.3771,
      "region": "seattle",
      "cluster": "interbay",
      "corridor": null,
      "beds": 1,
      "baths": 1,
      "rentMin": 1554,
      "rentMax": 1719,
      "rangeNote": "garage ~$125\u2013175/mo; RUBS ~$120\u2013180",
      "available": "many units",
      "parking": "garage",
      "parkingFee": 125,
      "parkingFeeMax": 175,
      "ev": "listing",
      "utils": "RUBS ~$120\u2013180",
      "pets": "unknown",
      "commuteA": "AM ~30\u201340 min via 520/Ballard",
      "commuteB": "Best B: walk / short D Line ~10\u201320 min",
      "notes": "Interbay walk-to-Expedia. Confirm EV stall fees.",
      "fit": "stretch",
      "url": "https://www.rentcafe.com/apartments/wa/seattle/the-flats-at-interbay/default.aspx"
    },
    {
      "id": "1br-bertona-7",
      "name": "Bertona Apt #7",
      "complex": "Bertona",
      "address": "2014 W Bertona St #7, Seattle, WA 98199",
      "lat": 47.6506,
      "lng": -122.3828,
      "region": "seattle",
      "cluster": "interbay",
      "corridor": null,
      "beds": 1,
      "baths": 1,
      "rentMin": 1675,
      "rentMax": 1675,
      "rangeNote": "W/S/G ~$85/resident",
      "available": "likely gone / off-market",
      "parking": "off-street",
      "parkingFee": 0,
      "ev": "no",
      "utils": "W/S/G ~$85/resident",
      "pets": "unknown",
      "commuteA": "AM ~30\u201340 min",
      "commuteB": "walk/D to Expedia ~15\u201325 min",
      "notes": "Sep 5 2026: carried as gone from Sep 4 recheck (HotPads/off-market). Do not tour until reconfirmed.",
      "fit": "gone",
      "url": "https://hotpads.com/2014-w-bertona-st-seattle-wa-98199-skkwtp/7/pad"
    },
    {
      "id": "1br-magnolia-vista",
      "name": "Magnolia Vista 1BR",
      "complex": "Magnolia Vista",
      "address": "3711 27th Pl W, Seattle, WA 98199",
      "lat": 47.6533,
      "lng": -122.3916,
      "region": "seattle",
      "cluster": "magnolia",
      "corridor": null,
      "beds": 1,
      "baths": 1,
      "rentMin": 1595,
      "rentMax": 1595,
      "rangeNote": "1 month free; units #102/#404",
      "available": "now",
      "parking": "covered/uncovered ~$50+/space",
      "parkingFee": 50,
      "ev": "no",
      "utils": "W/S/G flat ~$100 + $50/addl; SCL",
      "pets": "unknown",
      "commuteA": "AM ~32\u201342 min",
      "commuteB": "bus to D / Interbay ~20\u201330 min",
      "notes": "Same Magnolia pocket as 2BR hunt.",
      "fit": "stretch",
      "url": "https://www.rentable.co/seattle-wa"
    },
    {
      "id": "1br-cresswell",
      "name": "Cresswell #203/#304",
      "complex": "Cresswell",
      "address": "3023 14th Ave W, Seattle, WA 98119",
      "lat": 47.6473,
      "lng": -122.3754,
      "region": "seattle",
      "cluster": "interbay",
      "corridor": null,
      "beds": 1,
      "baths": 1,
      "rentMin": 1595,
      "rentMax": 1695,
      "rangeNote": null,
      "available": "now",
      "parking": "reserved on-site",
      "parkingFee": null,
      "ev": "no",
      "utils": "tenant utilities",
      "pets": "unknown",
      "commuteA": "AM ~30\u201340 min",
      "commuteB": "1 block from 15th/D Line \u2192 Expedia ~15\u201325 min",
      "notes": "Queen Anne West / Interbay. Strong B.",
      "fit": "stretch",
      "url": "https://northwest.appfolio.com"
    },
    {
      "id": "1br-taylor",
      "name": "1800 Taylor Ave N condo",
      "complex": "1800 Taylor",
      "address": "1800 Taylor Ave N, Seattle, WA 98109",
      "lat": 47.6354,
      "lng": -122.3456,
      "region": "seattle",
      "cluster": "interbay",
      "corridor": null,
      "beds": 1,
      "baths": 1,
      "rentMin": 1575,
      "rentMax": 1575,
      "rangeNote": "assigned parking extra; ~$75+$50 utils",
      "available": "active",
      "parking": "assigned extra / street",
      "parkingFee": null,
      "ev": "no",
      "utils": "~$75 first + $50 each; SCL",
      "pets": "unknown",
      "commuteA": "AM ~25\u201335 min via 520",
      "commuteB": "QA \u2192 D / Interbay ~25\u201340 min",
      "notes": "East Queen Anne. Same building as prior 2BR unit.",
      "fit": "stretch",
      "url": "https://www.rentalsource.com/details/1800-taylor-ave-n-seattle-wa-83879430/"
    },
    {
      "id": "1br-avia-202",
      "name": "Avia #202",
      "complex": "Avia",
      "address": "11534 Greenwood Ave N #202, Seattle, WA 98133",
      "lat": 47.7133,
      "lng": -122.3551,
      "region": "seattle",
      "cluster": "greenwood",
      "corridor": null,
      "beds": 1,
      "baths": 1,
      "rentMin": 1550,
      "rentMax": 1550,
      "rangeNote": "1 month free",
      "available": "now",
      "parking": "reserved",
      "parkingFee": 0,
      "ev": "no",
      "utils": "W/S/G $100+$50; SCL",
      "pets": "unknown",
      "commuteA": "AM ~30\u201340 min",
      "commuteB": "E Line / buses \u2192 downtown \u2192 D ~40\u201355 min",
      "notes": "Greenwood. EV no.",
      "fit": "stretch",
      "url": "https://www.aviaapartmentsseattle.com/"
    },
    {
      "id": "1br-9244-greenwood",
      "name": "9244 Greenwood #2",
      "complex": "9244 Greenwood",
      "address": "9244 Greenwood Ave N #2, Seattle, WA 98103",
      "lat": 47.6973,
      "lng": -122.355,
      "region": "seattle",
      "cluster": "greenwood",
      "corridor": null,
      "beds": 1,
      "baths": 1,
      "rentMin": 1300,
      "rentMax": 1325,
      "rangeNote": "Unit 2 $1,300 / Unit 5 $1,325; one uncovered parking",
      "available": "now",
      "parking": "uncovered assigned",
      "parkingFee": 50,
      "ev": "no",
      "utils": "electric + WSG ~$93/person",
      "pets": "unknown",
      "commuteA": "AM ~30\u201340 min",
      "commuteB": "E Line corridor \u2192 D ~40\u201355 min",
      "notes": "Sep 8 2026: still live on Rentable \u2014 Unit 2 $1,300 / Unit 5 $1,325 now. One cat; no dogs. EV unknown. Sep 9 recheck: still live at prior rent on Rentable.",
      "fit": "budget",
      "url": "https://www.rentable.co/seattle-wa/9244-greenwood-ave-n"
    },
    {
      "id": "1br-capri",
      "name": "Capri Apartments 1BR",
      "complex": "Capri",
      "address": "21416 52nd Ave W, Mountlake Terrace, WA 98043",
      "lat": 47.8044,
      "lng": -122.3033,
      "region": "seattle",
      "cluster": "mountlake-terrace",
      "corridor": "1-line-north",
      "beds": 1,
      "baths": 1,
      "rentMin": 1499,
      "rentMax": 1695,
      "rangeNote": "650 sf; 2 mo free on select (verify applies to 1BR)",
      "available": "now / Sep\u2013Nov 2026",
      "parking": "on-site",
      "parkingFee": 0,
      "ev": "unknown",
      "utils": "unknown",
      "pets": "unknown",
      "commuteA": "AM ~25\u201340 min I-5 \u2192 522/405; 3pm ~20\u201332",
      "commuteB": "~1.3 mi to MLT Link then 1 Line + D. ~55\u201375 min.",
      "notes": "Sep 8 2026: 1BRs still from $1,499+ (many now / Sep\u2013Nov); 2 months free on select. EV unknown. Sep 9 recheck: still live at prior rent on Rentable.",
      "fit": "budget",
      "url": "https://www.rentable.co/mountlake-terrace-wa/capri-apartments"
    },
    {
      "id": "1br-elevate",
      "name": "Elevate 1BR",
      "complex": "Elevate Lynnwood",
      "address": "4800 168th St SW, Lynnwood, WA 98037",
      "lat": 47.846449,
      "lng": -122.298264,
      "region": "seattle",
      "cluster": "lynnwood",
      "corridor": "1-line-north",
      "beds": 1,
      "baths": 1,
      "rentMin": 1695,
      "rentMax": 1695,
      "rangeNote": "717 sf",
      "available": "now / 7 Oct 2026",
      "parking": "carport or garage (paid)",
      "parkingFee": 55,
      "ev": "unknown",
      "utils": "tenant (typical)",
      "pets": "dogs/cats OK (fees)",
      "commuteA": "AM ~28\u201345 min I-5/522/405; 3pm ~22\u201335",
      "commuteB": "Bus toward Lynnwood City Center Link, then 1 Line + D. ~65\u201390 min.",
      "notes": "Sep 8 2026: 1BRs still from $1,695+ (A12/K05 now; K08 Oct 7); 1 month free + waived fees on select. EV unknown. Sep 9 recheck: still live at prior rent on Rentable.",
      "fit": "stretch",
      "url": "https://www.rentable.co/lynnwood-wa/elevate"
    },
    {
      "id": "1br-cinebar",
      "name": "Cinebar Apartments",
      "complex": "Cinebar",
      "address": "3250 15th Ave W, Seattle, WA 98119",
      "lat": 47.6501176,
      "lng": -122.3757828,
      "region": "seattle",
      "cluster": "interbay",
      "corridor": "interbay-15th",
      "beds": 1,
      "baths": 1,
      "rentMin": 1195,
      "rentMax": 1495,
      "rangeNote": "Rentable shows 1BR from $1,195 (page last-updated >1 mo \u2014 verify with PM); prior band ~$1,350\u2013$1,495",
      "available": "now",
      "parking": "free onsite (listing)",
      "parkingFee": 0,
      "ev": "unknown",
      "utils": "WSG via RUBS",
      "pets": "cats/small dogs; $35/mo + $400 deposit",
      "commuteA": "Drive to Kirkland via 520 \u2014 longer AM than Eastside (~30\u201345+)",
      "commuteB": "Excellent: Interbay / 15th Ave W near Expedia (~5\u201315 min walk/bus)",
      "notes": "Sep 9 2026: Rentable headline $1,195 but \u201cupdated over 1 month ago / contact PM\u201d. Keep verifying before touring. Strong Interbay location for B. EV unknown.",
      "fit": "budget",
      "url": "https://www.rentable.co/seattle-wa/cinebar-apartments"
    },
    {
      "id": "1br-ivy-interbay",
      "name": "Ivy at Interbay 1BR",
      "complex": "Ivy at Interbay",
      "address": "3008 16th Ave W, Seattle, WA 98119",
      "lat": 47.6473,
      "lng": -122.377,
      "region": "seattle",
      "cluster": "interbay",
      "corridor": "interbay-15th",
      "beds": 1,
      "baths": 1,
      "rentMin": 1793,
      "rentMax": 1793,
      "rangeNote": "Rentable shows live 1BRs from $1,793+ (was ~$1,842\u2013$1,877); studios from ~$1,543",
      "available": "now",
      "parking": "app-controlled parking (paid \u2014 confirm)",
      "parkingFee": null,
      "ev": "unknown",
      "utils": "confirm monthly fees in total price",
      "pets": "cats/dogs OK",
      "commuteA": "AM ~25\u201340 min over 520/I-5 to LWHS; 3pm ~20\u201335",
      "commuteB": "RapidRide D steps away \u2014 excellent for Expedia (~15\u201330 min)",
      "notes": "Sep 9 2026: still 1BRs from $1,793+; studios from $1,543; up to 4 weeks free. 2BRs all rented.",
      "fit": "stretch",
      "url": "https://www.rentable.co/seattle-wa/ivy-at-interbay"
    },
    {
      "id": "1br-crane-interbay",
      "name": "Crane at Interbay 1BR",
      "complex": "Crane at Interbay",
      "address": "3200 16th Ave W, Seattle, WA 98119",
      "lat": 47.649,
      "lng": -122.377,
      "region": "seattle",
      "cluster": "interbay",
      "corridor": "interbay-15th",
      "beds": 1,
      "baths": 1,
      "rentMin": 1695,
      "rentMax": 1695,
      "rangeNote": "700 sf; income-restricted / IZ \u2014 confirm eligibility",
      "available": "now",
      "parking": "garage (confirm fee)",
      "parkingFee": null,
      "ev": "unknown",
      "utils": "tenant pays utilities (listing)",
      "pets": "pets allowed (1 max per listing)",
      "commuteA": "AM ~25\u201340 min over 520/I-5 to LWHS; 3pm ~20\u201335",
      "commuteB": "Interbay \u2014 strong for Expedia / D Line",
      "notes": "Sep 7 2026: AffordableHousing.com still $1,695 income-restricted IZ; available now. Confirm eligibility. EV unknown.",
      "fit": "stretch",
      "url": "https://www.affordablehousing.com/seattle-wa/3200-16th-ave-w-1031805/"
    },
    {
      "id": "1br-alexandra-interbay",
      "name": "Alexandra Apartments",
      "complex": "Alexandra",
      "address": "2834 15th Ave W, Seattle, WA 98119",
      "lat": 47.6458,
      "lng": -122.3762,
      "region": "seattle",
      "cluster": "interbay",
      "corridor": "interbay-15th",
      "beds": 1,
      "baths": 1,
      "rentMin": 1475,
      "rentMax": 1475,
      "rangeNote": "650 sf; Unit 202 now / Unit 201 Sep 10",
      "available": "now / 10 Sep 2026",
      "parking": "confirm on-site",
      "parkingFee": null,
      "ev": "unknown",
      "utils": "confirm",
      "pets": "unknown",
      "commuteA": "AM ~25\u201340 min over 520/I-5 to LWHS; 3pm ~20\u201335",
      "commuteB": "Excellent: Interbay / 15th Ave W near Expedia / D Line",
      "notes": "Sep 8 2026: still Unit 202 $1,475 now / Unit 201 $1,475 Sep 10 on Rentable. Strong budget for B. EV unknown. Sep 9 recheck: still live at prior rent on Rentable.",
      "fit": "budget",
      "url": "https://www.rentable.co/seattle-wa/alexandra-apartments"
    },
    {
      "id": "1br-3425-14th",
      "name": "3425 14th Ave W \u2014 Unit 304",
      "complex": "3425 14th Ave W",
      "address": "3425 14th Ave W, Seattle, WA 98119",
      "lat": 47.6512,
      "lng": -122.3755,
      "region": "seattle",
      "cluster": "interbay",
      "corridor": "interbay-15th",
      "beds": 1,
      "baths": 1,
      "rentMin": 1649,
      "rentMax": 1649,
      "rangeNote": "650 sf",
      "available": "15 Sep 2026",
      "parking": "confirm",
      "parkingFee": null,
      "ev": "unknown",
      "utils": "confirm",
      "pets": "dogs/cats OK (listing)",
      "commuteA": "AM ~25\u201340 min over 520/I-5 to LWHS; 3pm ~20\u201335",
      "commuteB": "Interbay \u2014 strong for Expedia / D Line",
      "notes": "Sep 8 2026: Unit 304 still $1,649 available Sep 15 on Rentable. EV unknown. Sep 9 recheck: still live at prior rent on Rentable.",
      "fit": "stretch",
      "url": "https://www.rentable.co/seattle-wa/3425-14th-ave-w"
    }
  ]
};
